name: 'osm_walkability'
version: '1.0.0'
config-version: 2

profile: 'osm_walkability'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  osm_walkability:
