version: 2
sources:
  - name: osm
    database: bigquery-public-data
    schema: geo_openstreetmap
    tables:
      - name: planet_nodes

  - name: vancouver
    database: osm-walkability
    schema: vancouver
    tables:
      - name: storefronts_inventory
        description: '{{ doc("storefronts_inventory") }}'
